Align visually typeahead answer with other components
kbss-cvut/s-forms pull request #263
Opened 2024-01-29 14:37 UTC by LaChope

Resolves #257

2024-01-31 12:02 UTC, blcham requested changes
See my comments.

2024-01-31 12:04 UTC, blcham commented
also note there are some issues in chrome

2024-02-01 09:04 UTC, LaChope commented on src/components/answer/TypeaheadAnswer.jsx
> +  const valueRenderer = (children) => <>{children}</>;
Agree with `noLinksValueRenderer`

2024-02-01 09:13 UTC, LaChope commented on src/constants/Constants.js
> +  static IS_NOT_LINK = "http://onto.fel.cvut.cz/ontologies/form/is-not-link";
Agreed, done

2024-02-01 13:18 UTC, blcham approved these changes

2024-02-01 13:18 UTC, blcham commented on src/components/answer/TypeaheadAnswer.jsx
> +  // Used if the value should not be displayed as a link
```suggestion
```

2024-02-01 13:18 UTC, merged